// Every error code the API returns (build guide Section 6.4). Published in the OpenAPI spec so the frontend
// can map codes to messages. Add new codes here only.
export enum ErrorCode {
  VALIDATION_FAILED = "VALIDATION_FAILED",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  STALE_VERSION = "STALE_VERSION",
  PRECONDITION_REQUIRED = "PRECONDITION_REQUIRED",
  IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED",
  IDEMPOTENCY_IN_PROGRESS = "IDEMPOTENCY_IN_PROGRESS",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
  RATE_LIMITED = "RATE_LIMITED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",

  // Products, policies
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  POLICY_NOT_FOUND = "POLICY_NOT_FOUND",
  POLICY_OVERLAP = "POLICY_OVERLAP",

  // Registrations
  REGISTRATION_DUPLICATE_SERIAL = "REGISTRATION_DUPLICATE_SERIAL",
  REGISTRATION_NOT_FOUND = "REGISTRATION_NOT_FOUND",
  SERIAL_FORMAT_INVALID = "SERIAL_FORMAT_INVALID",
  PURCHASE_IN_FUTURE = "PURCHASE_IN_FUTURE",
  PURCHASE_BEFORE_LAUNCH = "PURCHASE_BEFORE_LAUNCH",
  PROOF_OF_PURCHASE_REQUIRED = "PROOF_OF_PURCHASE_REQUIRED",
  CUSTOMER_REQUIRED = "CUSTOMER_REQUIRED",
  CERTIFICATE_NOT_READY = "CERTIFICATE_NOT_READY",
  IMPORT_TOO_LARGE = "IMPORT_TOO_LARGE",

  // Claims
  CLAIM_INVALID_TRANSITION = "CLAIM_INVALID_TRANSITION",
  CLAIM_NOT_EDITABLE = "CLAIM_NOT_EDITABLE",
  PHOTO_REQUIRED = "PHOTO_REQUIRED",
  MESSAGE_REQUIRED = "MESSAGE_REQUIRED",
  RESOLUTION_REQUIRED = "RESOLUTION_REQUIRED",
  REASON_REQUIRED = "REASON_REQUIRED",
  FAILURE_DATE_INVALID = "FAILURE_DATE_INVALID",
  ASSIGNEE_INVALID = "ASSIGNEE_INVALID",

  // RMA
  RMA_INVALID_TRANSITION = "RMA_INVALID_TRANSITION",
  REPLACEMENT_SERIAL_REQUIRED = "REPLACEMENT_SERIAL_REQUIRED",
  CREDIT_AMOUNT_REQUIRED = "CREDIT_AMOUNT_REQUIRED",

  // Attachments
  ATTACHMENT_INVALID = "ATTACHMENT_INVALID",
  ATTACHMENT_NOT_CLEAN = "ATTACHMENT_NOT_CLEAN",
  ATTACHMENT_UPLOAD_MISMATCH = "ATTACHMENT_UPLOAD_MISMATCH",
}
