import { createReadStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import type { Readable } from "node:stream";
import { BlobStorage } from "./blob-storage";

/** Files in a local folder. Development and tests only (refused in production by env validation). */
export class LocalBlobStorage extends BlobStorage {
  private readonly root: string;

  constructor(dir: string) {
    super();
    this.root = resolve(dir);
  }

  /** Keys are generated by the API, but never let one escape the root folder. */
  private path(key: string): string {
    const full = resolve(this.root, key);
    if (!full.startsWith(this.root + sep)) throw new Error(`Invalid storage key: ${key}`);
    return full;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const path = this.path(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
  }

  async getStream(key: string): Promise<Readable | null> {
    const path = this.path(key);
    try {
      await stat(path);
    } catch {
      return null;
    }
    return createReadStream(path);
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }

  async ensureReady(): Promise<void> {
    await mkdir(this.root, { recursive: true });
  }
}
